---
pagetitle: Consultancy Enquiries | Henrique Costa
name: Consultancy Enquiries
page-layout: article
format: 
  html: 
    grid:
      margin-width: 0px
      sidebar-width: 0px

header-includes: >
  <link rel="stylesheet" href="../assets/contact.css">
resources:
  - ../assets/contact.css

comments: false
---

::: {.grid}

::: {.g-col-5 #note}

# Consultancy {{< fa feather-pointed >}}

I am open, mainly, to consultancy for risk assessment (methods and models).

If you want to make sure you are using your data (work or research) to its full potential, please contact me! I have an M.Sc. in applied economics, I have applied methods and models in all my professional experiences, I have spent more than 500 hours teaching university students (as a TA and monograph advisor in an MBA in Data Science & Analytics) and my friends You can testify that I can talk about R effortlessly for days!

If you want to hire me, here is a short list of things I can do for you:

- Research project
- Statistical inference
- Machine Learning
- Data visualization
- Scientific communication
- Financial & Non-Financial Risk Management

Please use this form for all enquiries about consultancy, collaborations, or speaking engagements.

<!-- <a class="link-dark me-1" href="https://fosstodon.org/@paulj1989" title="mastodon" target="_blank" rel="noopener">{{< fa brands mastodon >}}</a> -->
<!-- <a class="link-dark me-1" href="https://linkedin.com/in/paulj1989" title="LinkedIn" target="_blank"rel="noopener">{{< fa brands linkedin >}}</a> -->
<!-- <a class="link-dark me-1" href="https://github.com/paulj1989" title="github" target="_blank"rel="noopener">{{< fa brands github >}}</a> -->
<!-- <a class="link-dark me-1" href="https://kaggle.com/paulrjohnson" title="github" target="_blank"rel="noopener">{{< fa brands kaggle >}}</a> -->
<!-- <a class="link-dark me-1" href="https://scholar.google.com/citations?user=Op4yo3YAAAAJ&hl=en" title="Google Scholar" target="_blank"rel="noopener">{{< iconify fa6-brands google-scholar >}}</a> -->

:::
<!-- source: https://github.com/mccarthy-m-g/tidytales/blob/main/about/index.qmd#L24-L46 -->

::: {.g-col-1}
:::

::: {.g-col-6 #form}

<form action="https://formspree.io/f/mnqonanl" method="POST" accept-charset="utf-8">


<label for="full-name">Full Name</label>
<input type="text" name="name" id="full-name" class="form-control" placeholder="First and Last" required>

<label for="email-address">Email Address</label>
<input type="email" name="_replyto" id="email-address" class="form-control" placeholder="your@email.here" required>

<label for="message">Message</label>
  <textarea rows="15" name="message" id="message" class="form-control" placeholder="Type your message here" required></textarea>

<button type="submit" class="btn btn-primary mt-4">Send message</button>
</form>
:::

:::
<!-- end grid -->